
<!-- # Preface {-} -->

This is a proposal for a course formed under the auspices of the *Astin Academy*. The proposal has been approved for adoption by the Astin Board. A [call for volunteers](https://www.actuaries.org/IAA/Documents/ASTIN/Newsletters/2020/ASTIN%20Newsletter_Oct%202020_Final.pdf) has gone out.

**Course**: A non-synchronous experience that covers the fundamentals of loss data modeling. The course will provide an interactive learning experience through online video explanations, quizzes, and software (`R`) demonstrations to sharpen student understanding. It may be also used by an in-person instructor who employs a hybrid teaching model that combines this resource with an in-person experience.

**The Audience**: Beginning actuarial students who may not have had an exposure to industry practice. The course assumes that participants have a background in loss data modeling, presumably through reading the book Loss Data Analytics. 

**The Method of Delivery**. A web based course hosted on a free server such as Github. The course will include links to videos (that would be hosted on another free server such as Kaltura), and interactive `R` tutorials, powered by a free server such as Datacamp. The course places a premium on inter-activity - the cost for this is that it presumes ready access to the internet. (Note that in jurisdictions without steady internet access, the book Loss Data Analytics can be downloaded as a .pdf file.)

**The Price for Course Participants**. Zero. This foundation course is geared to aid the development of future generations of actuaries on a worldwide basis.

**Course Design**. The design mimics one developed for a [regression course](https://ewfreesres.github.io/RegressModel/index.html) that can complement/substitute for in-person teaching. This online course is authored in `R` (specifically, using a package called **bookdown**), has many interactive features using html/javascript, links to videos located at a free site (Kaltura), and interactive scripts using an `R` package called **Datacamp Lite** (written and powered by Datacamp). The course itself is hosted on a free Github site. 

Instead of regression, the new proposed course will be based on loss data modeling. As background, students can rely on the freely available book [Loss Data Analytics](https://openacttexts.github.io/). This book is written by an [international author team](https://openacttexts.github.io/Loss-Data-Analytics/index.html#contributors) and follows IAA guidelines on topics. Specifically, the initial version of the proposed course will cover the first five chapters of *Loss Data Analytics*. For each section of each chapter, there will be 

*  a video overview (generally 3-8 minutes long), 
*  overheads and scripts for viewing/reviewing the video, 
*  a quiz, and 
** one or more interactive `R` tutorials. 

Including a start and wrap-up of the course, there will be approximately 26 video segments (=1+3+7+5+4+5+1, 1 to start, 3 for chapter 1, 7 for chapter 2, and so on). After having read the book, participants would be able to complete the course in about a day. As an added bonus, we might include industry case studies as additional segments.

**Strategy for Content Development**. The team would be directed by a steering committee, presumably about 3-5 people. Co-chair Miyuki Ebisaki will serve as liaison to the ASTIN council. The steering committee would be responsible for the overall content of the course (the syllabus), attracting appropriate volunteers, managing the progress, and marketing. Members of the steering committee will do the beginning and wrap-up videos.

To develop the content, for each chapter we will organize a content team. Specifically, we would need 

*  one person responsible for videos, 
*  one for the design of the interactive `R` questions, and 
*  one to engineer the feedback mechanism for the `R` questions (a time consuming task). 

All chapter members could contribute to the quizzes. If there are five chapters, this represents 15 (=3 x 5) volunteer positions. Presumably, some volunteers would be up for doing more than one chapter.

Additional volunteers that would be nice but not essential:

*  An expert in `R` who knows the details of package development/deployment and interactions with html/javascript
*  An expert in html/javascript who could help with the integration of RStudio/bookdown
*  An expert in creating videos (including closed-captioning) and how to host them 
*  An expert in git/Github who could guide us in collaborative development

After the initial version is complete, we will discuss extensions to include other chapters.

**Timeline**. As this is a pilot project, quality is more important than speed. 

*  This course covers the foundations that do not change all that quickly, so we want a product that can serve the profession on a long-term basis. 
*  To promote sustainability, we want a quality product that our customers, the students, enjoy and find useful. 
*  If this is to be a model that the Astin Academy uses as a basis for other courses, we want to get young colleagues involved and have them take ownership. 

All of these aspects point to taking time. Having said that, the design is straightforward and already accomplished in the regression course mentioned above. So, an approximate completion date is six months after the volunteers have been recruited, presumably sometime during the summer of 2021.


#### Interested? {-}

If you are interested in participating, please write the co-chairs of the *Astin Academy*:

*  Edward W. (Jed) Frees <jfrees@bus.wisc.edu>
*  Miyuki Ebisaki <mebisaki@sompo-ri.co.jp>
